
Epoch: [1/30]	Loss: 0.0011
Epoch: [2/30]	Loss: 0.0000
Epoch: [3/30]	Loss: 0.0001
Epoch: [4/30]	Loss: 0.0000
Epoch: [5/30]	Loss: 0.0000
Epoch: [6/30]	Loss: 0.0000
Epoch: [1/20]	Loss: 0.1707
Epoch: [2/20]	Loss: 0.0013
Epoch: [3/20]	Loss: 0.0100
Epoch: [4/20]	Loss: 0.0015
Epoch: [5/20]	Loss: 0.0194
Epoch: [6/20]	Loss: 0.0084
Epoch: [7/20]	Loss: 0.0266
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 378, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 388, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7f0fedf24ca0> (for pre_run_cell):