2022-01-20 13:31:06,415 INFO    MainThread:23802 [wandb_setup.py:_flush():71] setting env: {}
2022-01-20 13:31:06,415 INFO    MainThread:23802 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-20 13:31:06,416 INFO    MainThread:23802 [wandb_init.py:_log_setup():371] Logging user logs to /home/huynth/pytorch_practice/wandb/run-20220120_133106-2bxi138t/logs/debug.log
2022-01-20 13:31:06,416 INFO    MainThread:23802 [wandb_init.py:_log_setup():372] Logging internal logs to /home/huynth/pytorch_practice/wandb/run-20220120_133106-2bxi138t/logs/debug-internal.log
2022-01-20 13:31:06,416 INFO    MainThread:23802 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0fedece880>
2022-01-20 13:31:06,417 INFO    MainThread:23802 [wandb_init.py:init():404] calling init triggers
2022-01-20 13:31:06,417 INFO    MainThread:23802 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-20 13:31:06,417 INFO    MainThread:23802 [wandb_init.py:init():460] starting backend
2022-01-20 13:31:06,417 INFO    MainThread:23802 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-20 13:31:06,461 INFO    MainThread:23802 [backend.py:ensure_launched():216] starting backend process...
2022-01-20 13:31:06,503 INFO    MainThread:23802 [backend.py:ensure_launched():221] started backend process with pid: 26796
2022-01-20 13:31:06,505 INFO    MainThread:23802 [wandb_init.py:init():469] backend started and connected
2022-01-20 13:31:06,538 INFO    MainThread:23802 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-20 13:31:06,539 INFO    MainThread:23802 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-20 13:31:06,539 INFO    MainThread:23802 [wandb_init.py:init():533] updated telemetry
2022-01-20 13:31:06,653 INFO    MainThread:23802 [wandb_init.py:init():563] communicating current version
2022-01-20 13:31:08,682 INFO    MainThread:23802 [wandb_init.py:init():568] got version response 
2022-01-20 13:31:08,682 INFO    MainThread:23802 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-20 13:31:09,121 INFO    MainThread:23802 [wandb_init.py:init():606] starting run threads in backend
2022-01-20 13:31:14,132 INFO    MainThread:23802 [wandb_run.py:_console_start():1810] atexit reg
2022-01-20 13:31:14,133 INFO    MainThread:23802 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-20 13:31:14,134 INFO    MainThread:23802 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-20 13:31:14,136 INFO    MainThread:23802 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-20 13:31:14,137 INFO    MainThread:23802 [wandb_init.py:init():633] run started, returning control to user process
2022-01-20 13:31:14,144 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:31:14,145 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:34:40,317 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:34:40,320 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:34:40,323 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:43:38,899 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:43:38,956 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:43:38,956 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:44:45,748 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:44:45,781 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:44:45,781 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:45:16,803 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:45:17,354 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:45:17,354 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:48:09,138 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:48:09,214 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:48:09,214 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:48:14,135 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:52:58,346 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:52:58,346 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:54:30,909 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:59:18,921 INFO    MainThread:23802 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-20 13:59:18,922 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:59:42,132 INFO    MainThread:23802 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-20 13:59:42,203 INFO    MainThread:23802 [wandb_setup.py:_flush():71] setting env: {}
2022-01-20 13:59:42,203 INFO    MainThread:23802 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-20 13:59:42,203 INFO    MainThread:23802 [wandb_init.py:_log_setup():371] Logging user logs to /home/huynth/pytorch_practice/wandb/run-20220120_135942-1yhleghb/logs/debug.log
2022-01-20 13:59:42,204 INFO    MainThread:23802 [wandb_init.py:_log_setup():372] Logging internal logs to /home/huynth/pytorch_practice/wandb/run-20220120_135942-1yhleghb/logs/debug-internal.log
2022-01-20 13:59:42,204 INFO    MainThread:23802 [wandb_init.py:init():404] calling init triggers
2022-01-20 13:59:42,204 INFO    MainThread:23802 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-20 13:59:42,204 INFO    MainThread:23802 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 2bxi138t
2022-01-20 13:59:42,206 INFO    MainThread:23802 [wandb_run.py:finish():1457] finishing run huynth18/mnist-pytorch/2bxi138t
2022-01-20 13:59:42,207 INFO    MainThread:23802 [jupyter.py:save_history():429] not saving jupyter history
2022-01-20 13:59:42,207 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 13:59:42,207 INFO    MainThread:23802 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-20 13:59:42,208 INFO    MainThread:23802 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-20 13:59:42,209 INFO    MainThread:23802 [wandb_run.py:_restore():1752] restore
2022-01-20 13:59:42,652 INFO    MainThread:23802 [wandb_run.py:_restore():1752] restore
2022-01-20 13:59:42,673 ERROR   MainThread:23802 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/huynth/miniconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-20 14:02:39,847 INFO    MainThread:23802 [wandb_setup.py:_flush():71] setting env: {}
2022-01-20 14:02:39,847 INFO    MainThread:23802 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-20 14:02:39,847 INFO    MainThread:23802 [wandb_init.py:_log_setup():371] Logging user logs to /home/huynth/pytorch_practice/wandb/run-20220120_140239-332jijn5/logs/debug.log
2022-01-20 14:02:39,847 INFO    MainThread:23802 [wandb_init.py:_log_setup():372] Logging internal logs to /home/huynth/pytorch_practice/wandb/run-20220120_140239-332jijn5/logs/debug-internal.log
2022-01-20 14:02:39,847 INFO    MainThread:23802 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0fed8f2fa0>
2022-01-20 14:02:39,847 INFO    MainThread:23802 [wandb_init.py:init():404] calling init triggers
2022-01-20 14:02:39,848 INFO    MainThread:23802 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-20 14:02:39,848 INFO    MainThread:23802 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 2bxi138t
2022-01-20 14:02:39,849 INFO    MainThread:23802 [wandb_run.py:finish():1457] finishing run huynth18/mnist-pytorch/2bxi138t
2022-01-20 14:02:39,850 INFO    MainThread:23802 [jupyter.py:save_history():429] not saving jupyter history
2022-01-20 14:02:39,850 INFO    MainThread:23802 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-20 14:02:39,850 INFO    MainThread:23802 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
